default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tapes
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
  host: 'localhost'

development:
  <<: *default
  database: tapes_development

test:
  <<: *default
  database: tapes_test
