default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: spree_sample
  password: <%= ENV['DATABASE_PASSWORD'] %>
  timeout: 5000
  host: 'localhost'

development:
  <<: *default
  database: spree_sample_development

production:
  <<: *default
  database: spree_sample_production

test:
  <<: *default
  database: spree_sample_test
