development:
  adapter: postgresql
  encoding: unicode
  database: spree_development
  pool: 5
  username: root
  password: root
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: spree_test
  pool: 5
  username: root
  password: root
  timeout: 5000